### ISSUE TITLE
Invalid batch test

### ISSUE THREAD

**Issue by gitautas** [gitautas/emoji-identifiers#3]
The current batch test is not valid, it's just printing out a character. Perhaps someone with a windows machine could try the following:
```batch
@echo off
set 🐕=Woof
echo %🐕%
```
@shenanigansd perhaps you could check this out?

**Comment by shenanigansd** [comment]
Hello! Looks like you're correct. I sincerely apologize for my transgressions... I'll create a PR to fix this immediately!

```batch
PS C:\Users\BradleyReynolds\Downloads> ./old.bat

C:\Users\BradleyReynolds\Downloads>echo ≡ƒÉò
≡ƒÉò
PS C:\Users\BradleyReynolds\Downloads> ./new.bat
Woof
PS C:\Users\BradleyReynolds\Downloads>
```
